"""
Django settings for RemoteDomotic project.

Generated by "django-admin startproject" using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from os import getenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-00c^_n^h%m=yfbsmtpl(9uge^g@tv(3o-p)x$*$!upe4b3cj!o"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = int(
    getenv("DEBUG")
)

ALLOWED_HOSTS = [
    "127.0.0.1", "192.168.46.125", "192.168.1.8",
    "remotedomotic.local", "remotedomotic.sec",
    "localhost"
]

# Application definition

INSTALLED_APPS = [
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"websecurity.apps.WebsecurityConfig",
	"APIwebsecurity.apps.ApiwebsecurityConfig",
	"RemoteDomotic"
]

MIDDLEWARE = [
	"django.middleware.security.SecurityMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
	"django.middleware.locale.LocaleMiddleware"
]

ROOT_URLCONF = "RemoteDomotic.urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

WSGI_APPLICATION = "RemoteDomotic.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.sqlite3",
		"NAME": BASE_DIR / "RemoteDomotic.sqlite3",
	}
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#THE MODEL USED FOR MANAGING USERS
AUTH_USER_MODEL = "websecurity.Users"

#WHERE SAVE MEDIA FILE
MEDIA_URL = "/media/"
MEDIA_ROOT = f"{BASE_DIR}/{MEDIA_URL}"

#WHERE SAVE STATIC FILE
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = f"{BASE_DIR}/{STATIC_URL}"

#LOGIN REDIRECT FOR ALL LOGIN REQUIRED
LOGIN_URL = "/websecurity/login/"

#MAX FILE SIZE FOR AUDIO UPLOADING
MAX_FILE_SIZE = 2097152

#IOT devices configuration
iots_avalaibles = ["tapo", "IP WebCam App"]

iots = [
	(iot, iot)
	for iot in iots_avalaibles
]

#AVAILABLES CATEGORY
categories_avalaibles = ["WebCam", "Lamp", "Switch", "Door", "Lock"]

categories = [
	(category, category)
	for category in categories_avalaibles
]