# Generated by Django 3.2.4 on 2021-06-18 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import websecurity.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=88)),
                ('tries', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WebCam', 'WebCam'), ('Lamp', 'Lamp'), ('Switch', 'Switch'), ('Door', 'Door'), ('Lock', 'Lock')], default='WebCam', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, choices=[('rtsp', 'rtsp'), ('http', 'http'), ('https', 'https')], max_length=8, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=88, null=True)),
                ('video_path', models.CharField(blank=True, max_length=15, null=True)),
                ('audio_path', models.CharField(blank=True, max_length=15, null=True)),
                ('manufacturer', models.CharField(choices=[('tapo', 'tapo'), ('IP WebCam App', 'IP WebCam App')], default='tapo', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('permission', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='UP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permission', models.ForeignKey(db_column='id_permission', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='websecurity.permissions', verbose_name='permission')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'Users Permissions',
                'db_table': 'users_permissions',
                'unique_together': {('id_user', 'id_permission')},
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=88, null=True)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('device', models.CharField(max_length=25, unique=True)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='websecurity.categories', verbose_name='category')),
                ('id_manufacturer', models.ForeignKey(db_column='id_manufacturer', on_delete=django.db.models.deletion.CASCADE, to='websecurity.manufacturers', verbose_name='manufacturer')),
                ('id_room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, to='websecurity.rooms', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.ForeignKey(db_column='id_device', on_delete=django.db.models.deletion.CASCADE, to='websecurity.devices', verbose_name='device')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Belong',
                'verbose_name_plural': 'Belongs',
                'db_table': 'belongs',
                'unique_together': {('id_user', 'id_device')},
            },
        ),
        migrations.AddField(
            model_name='users',
            name='belongs',
            field=models.ManyToManyField(through='websecurity.B', to='websecurity.Devices', verbose_name='device'),
        ),
        migrations.AddField(
            model_name='users',
            name='permissions',
            field=models.ManyToManyField(through='websecurity.UP', to='websecurity.Permissions', verbose_name='permission'),
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fr', 'French'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('la', 'Latin'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('my', 'Myanmar (Burmese)'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('su', 'Sundanese'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tl', 'Filipino'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-CN', 'Chinese'), ('zh-TW', 'Chinese (Mandarin/Taiwan)'), ('zh', 'Chinese (Mandarin)')], default='it', max_length=15)),
                ('text', models.TextField(blank=True, max_length=50, null=True)),
                ('command', models.CharField(blank=True, max_length=20, null=True)),
                ('audio', models.FileField(blank=True, upload_to=websecurity.validators.get_file_path, validators=[websecurity.validators.validate_file])),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'db_table': 'commands',
                'unique_together': {('id_user', 'command')},
            },
        ),
    ]
